services:
  campeonato-db:
    container_name: campeonato-db
    image: "postgres:14.4-alpine"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: campeonato
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
